export const AuthActionTypes = {
    LOGIN_PROG: 'LOGIN_PROG',
    LOGIN_SUCC: 'LOGIN_SUCC',
    LOGIN_FAIL: 'LOGIN_FAIL',

    REGISTER_PROG: 'REGISTER_PROG',
    REGISTER_SUCC: 'REGISTER_SUCC',
    REGISTER_FAIL: 'REGISTER_FAIL',


    SET_USER: 'SET_USER',

    LOGOUT: 'LOGOUT',

    CLEAR_ERROR: 'CLEAR_ERROR',




};