export const AuthActionTypes = {
    LOGIN_PROG: 'LOGIN_PROG',
    LOGIN_SUCC: 'LOGIN_SUCC',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SET_USER: 'SET_USER',

    LOGOUT: 'LOGOUT',

    CLEAR_ERROR: 'CLEAR_ERROR',

    GET_PROFILE_PROG: 'GET_PROFILE_PROG',
    GET_PROFILE_SUCC: 'GET_PROFILE_SUCC',
    GET_PROFILE_FAIL: 'GET_PROFILE_FAIL',

    UPDATE_PROFILE_PROG: 'UPDATE_PROFILE_PROG',
    UPDATE_PROFILE_SUCC: 'UPDATE_PROFILE_SUCC',
    UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
    CLEAR_SUCCESS: 'CLEAR_SUCCESS'

};