export const AuthActionTypes = {

    GET_AUTH_TOKEN_PROG: 'GET_AUTH_TOKEN_PROG',
    GET_AUTH_TOKEN_SUCC: 'GET_AUTH_TOKEN_SUCC',
    GET_AUTH_TOKEN_FAIL: 'GET_AUTH_TOKEN_FAIL',

    REGISTER_USER_PROG: 'REGISTER_USER_PROG',
    REGISTER_USER_SUCC: 'REGISTER_USER_SUCC',
    REGISTER_USER_FAIL: 'REGISTER_USER_FAIL',
    CLEAR_REGISTER_USER_SUCC: 'CLEAR_REGISTER_USER_SUCC',


    LOGIN_PROG: 'LOGIN_PROG',
    LOGIN_SUCC: 'LOGIN_SUCC',
    LOGIN_FAIL: 'LOGIN_FAIL',

    REGISTER_CUSTOMER_PROG: 'REGISTER_CUSTOMER_PROG',
    REGISTER_CUSTOMER_SUCC: 'REGISTER_CUSTOMER_SUCC',
    REGISTER_CUSTOMER_FAIL: 'REGISTER_CUSTOMER_FAIL',


    SET_USER: 'SET_USER',

    LOGOUT: 'LOGOUT',

    CLEAR_ERROR: 'CLEAR_ERROR',




};