export const ServiceHistoryActionTypes = {
    GET_SERVICE_HISTORY_PROG: 'GET_SERVICE_HISTORY_PROG',
    GET_SERVICE_HISTORY_SUCC: 'GET_SERVICE_HISTORY_SUCC',
    GET_SERVICE_HISTORY_FAIL: 'GET_SERVICE_HISTORY_FAIL',
};