export const SettingsActionTypes = {
    GET_SETTINGS_PROG: 'GET_SETTINGS_PROG',
    GET_SETTINGS_SUCC: 'GET_SETTINGS_SUCC',
    GET_SETTINGS_FAIL: 'GET_SETTINGS_FAIL',

    GET_CUSTOMER_INFO_PROG: 'GET_CUSTOMER_INFO_PROG',
    GET_CUSTOMER_INFO_SUCC: 'GET_CUSTOMER_INFO_SUCC',
    GET_CUSTOMER_INFO_FAIL: 'GET_CUSTOMER_INFO_FAIL',





};