export const ScheduleServiceActionTypes = {
    GET_SERVICES_PROG: 'GET_SERVICES_PROG',
    GET_SERVICES_SUCC: 'GET_SERVICES_SUCC',
    GET_SERVICES_FAIL: 'GET_SERVICES_FAIL',

    GET_PROVIDERS_PROG: 'GET_PROVIDERS_PROG',
    GET_PROVIDERS_SUCC: 'GET_PROVIDERS_SUCC',
    GET_PROVIDERS_FAIL: 'GET_PROVIDERS_FAIL',

    GET_AVAILABILITIES_PROG: 'GET_AVAILABILITIES_PROG',
    GET_AVAILABILITIES_SUCC: 'GET_AVAILABILITIES_SUCC',
    GET_AVAILABILITIES_FAIL: 'GET_AVAILABILITIES_FAIL',





};