export const VehicleActionTypes = {
    GET_VIN_SPECS_PROG: 'GET_VIN_SPECS_PROG',
    GET_VIN_SPECS_SUCC: 'GET_VIN_SPECS_SUCC',
    GET_VIN_SPECS_FAIL: 'GET_VIN_SPECS_FAIL',

    GET_VEHICLE_PRICE_PROG: 'GET_VEHICLE_PRICE_PROG',
    GET_VEHICLE_PRICE_SUCC: 'GET_VEHICLE_PRICE_SUCC',
    GET_VEHICLE_PRICE_FAIL: 'GET_VEHICLE_PRICE_FAIL',





};