export const LoyaltyActionTypes = {
    GET_REWARD_POINTS_PROG: 'GET_REWARD_POINTS_PROG',
    GET_REWARD_POINTS_SUCC: 'GET_REWARD_POINTS_SUCC',
    GET_REWARD_POINTS_FAIL: 'GET_REWARD_POINTS_FAIL',
};